### ISSUE TITLE
Change CameraFollowCharacter script to use max(Direction)

### ISSUE THREAD

**Issue by munkeyxis** [whoa-algebraic/game-off-2016#19]
### Expected behavior
When the character's position goes beyond the max(Direction) position, set the camera's position to max(Direction).

### Actual behavior
Camera's position is set to the character's last position before it changed to a position beyond max(Direction).

### Steps to reproduce the behavior
While running the game in the editor, manually change the characters position to be beyond one of the max direction positions. The camera will use the last position that the character had resulting in an inconsistent positioning when approaching the boundaries of a room. This can have an adverse effect if character teleporting is added or any rapid character position changes between frames happens.

**Comment by virtuoushub** [comment]
I haven't tested this issue yet, however I noticed [your comment](https://github.com/whoa-algebraic/game-off-2016/commit/fb65aa332bced912b27438d6e2677a52c06ec996#commitcomment-19780363). Does the code you updated fix this issue?

**Comment by virtuoushub** [comment]
Spoke with @munkeyxis 

This issue can be considered closed. If one wants to test 

> just run the basic_map scene and run through the open door
> you'll run through the open door on the left and then you'll see your character come out of a door on the right

This is the expected behavior
